# Use a imagem oficial do Node.js
FROM node:alpine

# Defina a pasta de trabalho no contêiner
WORKDIR /app

# Copie os arquivos do package.json e yarn.lock para o diretório de trabalho do seu novo contêiner
COPY package*.json yarn.lock ./

# Instale as dependências do projeto
RUN yarn

# Copie o resto dos arquivos do projeto para o diretório de trabalho do seu novo contêiner
COPY . .

# post install script
RUN yarn postinstall

# Generate prisma client and run prisma studio
RUN npx prisma generate

# Exponha a porta que o aplicativo usará
EXPOSE 3000

# Comando para iniciar o serviço
CMD ["yarn", "start:dev"]
